@host = localhost
@port = 3000
@apiversion = api/v1

### Recuperar Um Categoria por ID
GET http://{{host}}:{{port}}/{{apiversion}}/categorias/f2f20af9-e046-4347-84f1-f8e41a327695

### Recuperar Todas as Categorias
GET http://{{host}}:{{port}}/{{apiversion}}/categorias

### Inserir Uma Categoria
POST http://{{host}}:{{port}}/{{apiversion}}/categorias
Content-type: application/json

{
    "nome":"Sala de Estar"
}

### Atualizar Categoria
PUT http://{{host}}:{{port}}/{{apiversion}}/categorias/880a6e3e-ba35-4371-9a6d-2539b053082f
Content-type: application/json 

{
    "id": "880a6e3e-ba35-4371-9a6d-2539b053082f",
    "nome":"Sala de Televisão"
}

### Deletar Categoria
DELETE http://{{host}}:{{port}}/{{apiversion}}/categorias/3c30db75-5a96-40d9-83e0-f5d16a1af856

### Inserir Uma Categoria
POST http://{{host}}:{{port}}/{{apiversion}}/categorias
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNhZmM5NDNiLTdlYTgtNDIzNC1hOTNjLTRlZDExNjk2MzA1NCIsIm5vbWUiOiJQZWRybyIsImVtYWlsIjoicGVkcm9AbWFpbC5jb20iLCJ0aXBvIjoiQURNSU5JU1RSQURPUiIsImlhdCI6MTcwNTM2MTQ3MiwiZXhwIjoxNzA1MzY1MDcyfQ.tVLDBT752egLQZH5Ly1Oe6r6KGi3Knu8mQrgGE9n6KY

{
    "nome":"Sala de Televisão"
}